insert into pessoas values    #OUTRA FORMA DE INSERIR, POREM ESSA DEPENDE QUE OS DADOS INSERIDOS ESTEJAM NA ORDEM DAS COLUNAS DA TABELA
(DEFAULT, "JONH", "2000-05-21","M","83","1.8","AMERICANO"), #COMANDO DEFAULT É PQ O ID É AUTO_INCREMENT
(DEFAULT, "MARY", "2002-08-16","F","62","1.7","CANADENSE");

select *from pessoas;